In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np

Mounted at /content/drive


##Day 1: Sonar Sweep

In [ ]:
filelocation = '/content/drive/MyDrive/AdventOfCode/input1.txt'

file1 = np.loadtxt(filelocation)
print(file1[2])

In [ ]:
count = 0
num = file1[0]
for i in range(len(file1)):
  #print(FileContent[i])
  if file1[i] > num:
    count += 1
  num = file1[i]
print(count)

1228


In [ ]:
count = 0 
num = file1[0]+file1[1]+file1[2]
for i in range(len(file1)-2):
  sum = file1[i]+file1[i+1]+file1[i+2]
  if sum > num:
    count += 1
  num = sum
print(count) 

1257


##Day 2: Dive!

In [ ]:
filelocation = '/content/drive/MyDrive/AdventOfCode/input2.txt'
my_file = open(filelocation, "r")
content = my_file.readlines()
my_file.close()
print(content)

f = 0
d = 0
for i in content:
  if i[0] == 'f':
    n = int(i[8])
    f += n
  elif i[0] == 'd':
    a = int(i[5])
    d += a
  elif i[0] == 'u':
    u = int(i[3])
    d -= u
print(f*d)

['forward 7\n', 'forward 9\n', 'forward 9\n', 'down 3\n', 'down 8\n', 'down 3\n', 'forward 6\n', 'down 7\n', 'up 3\n', 'forward 3\n', 'up 3\n', 'down 3\n', 'down 9\n', 'down 6\n', 'forward 8\n', 'down 3\n', 'down 9\n', 'forward 4\n', 'forward 3\n', 'down 1\n', 'forward 2\n', 'down 5\n', 'forward 9\n', 'forward 6\n', 'up 1\n', 'forward 8\n', 'down 9\n', 'forward 8\n', 'down 7\n', 'down 9\n', 'down 4\n', 'down 2\n', 'forward 2\n', 'down 6\n', 'up 8\n', 'forward 3\n', 'forward 7\n', 'down 2\n', 'forward 4\n', 'down 3\n', 'down 1\n', 'down 8\n', 'forward 5\n', 'forward 6\n', 'down 3\n', 'forward 1\n', 'up 1\n', 'down 8\n', 'forward 5\n', 'forward 2\n', 'forward 9\n', 'up 4\n', 'down 1\n', 'down 3\n', 'up 5\n', 'up 5\n', 'forward 7\n', 'up 1\n', 'forward 8\n', 'forward 4\n', 'forward 3\n', 'down 9\n', 'forward 2\n', 'forward 5\n', 'down 5\n', 'up 7\n', 'forward 4\n', 'up 5\n', 'down 5\n', 'down 4\n', 'down 9\n', 'forward 1\n', 'up 3\n', 'forward 6\n', 'down 3\n', 'forward 9\n', 'down 1\n', 

In [ ]:
f = 0
d = 0
aim = 0
for i in content:
  if i[0] == 'f':
    n = int(i[8])
    f += n
    d += aim*n
  elif i[0] == 'd':
    a = int(i[5])
    aim += a
  elif i[0] == 'u':
    u = int(i[3])
    aim -= u
print(f*d)

2015547716


##Day 3: Binary Diagnostic

In [ ]:
filelocation = '/content/drive/MyDrive/AdventOfCode/input3.txt'
file1 = open(filelocation, "r")
content = file1.read().splitlines()
file1.close()


In [ ]:
length = len(content[0])
count1 = [0]*length
count0 = [0]*length
gamma, epsi = [0]*length, [0]*length
g, e = 0, 0
for i in content:
  for p in range(length):
    if i[p] == '1':
      count1[p]+=1
    else:
      count0[p]+=1

print(count1, count0)
for p in range(length):
  if count1[p] >= count0[p]:
    gamma[p] = 1
    g += 2**(length-p-1)
  else:
    epsi[p] = 1
    e += 2**(length-p-1)
print(gamma, epsi)
print(g*e)

In [ ]:
def partList(list1, position):
  if len(list1) == 1:
    return list1, list1
  one, zero = 0, 0
  listA,listB = [], []
  for i in list1:
    if i[position] == '1':
      one+=1
      listA.append(i)
    else:
      zero+=1
      listB.append(i)
  if one >= zero:
    popular = listA
    unpop = listB
  else:
    popular = listB
    unpop = listA
  print(len(popular), len(unpop))
  return popular, unpop

In [ ]:
def bintodec(a):
  l = len(a)-1
  num = 0
  for i in range(len(a)):
    num += 2**(len(a)-i-1)*int(a[i])
  return num

In [ ]:
popular = content.copy()
unpop = content.copy()
for p in range(length):
  popular,_= partList(popular, p)
  

for p in range(length):
  a, unpop = partList(unpop, p)

p = bintodec(popular[0])
u = bintodec(unpop[0])
print(p,u,p*u)



##Day4 - Giant Squid


In [ ]:
filePath = '/content/drive/MyDrive/AdventOfCode/input4.txt'

line1 = np.loadtxt(filePath, delimiter = ',', max_rows=1)
data = np.loadtxt(filePath, skiprows = 1)
board_size = len(data[0])

In [ ]:
def bingo(mtx, visited, num):
  bingo = False
  row, col  = mtx.shape  #500,5
  board, product = 0, 0
  for r in range(row): 
    board = r//col
    if np.sum(visited[r]) == col:
      bingo = True
      rest = np.ones([col,col]) - visited[board*5:board*5+col,:]
      product = np.sum(data[board*5:board*5+col,:]*rest)*num
    elif r%col == 0 and r+col <= row:
      for c in range(col):
        if np.sum(visited[r:r+col, c]) == col:
          bingo = True
          rest = np.ones([col,col]) - visited[board*5:board*5+col,:]
          product = np.sum(mtx[board*5:board*5+col,:]*rest)*num
  return bingo, product, board

In [ ]:
def which_win(mtx, visited, line1):
  row, col  = mtx.shape
  bingoo, product, board = False, 0, 0
  visited = np.zeros(mtx.shape)
  for num in line1:
    for r in range(row):
      for c in range(col):
        if mtx[r][c] == num:
          visited[r][c] = 1
          bingoo, product, board = bingo(mtx, visited, num)
          if bingoo == True:
            print(visited[board*5:board*5+col,:])
            print(data[board*5:board*5+col,:])
            return product, visited, board     
  return 0,0

In [ ]:
print(which_win(data,visited,line1))

In [ ]:
def which_lose(mtx, visited, line1):
  row, col  = mtx.shape
  bingoo, product_f, board = False, 0, 0
  visited = np.zeros(mtx.shape)
  not_won = np.ones(len(mtx), dtype=bool) #not won is true, won is false
  for num in line1:
    for r in range(row):
      board = r//5
      if not_won[r] == True:
        for c in range(col):
          if mtx[r][c] == num:
            visited[r][c] = 1
            bingoo, _ , _ = bingo(mtx[not_won], visited[not_won], num)
            if bingoo == True:
              bingoo = False
              rest = np.ones([len(mtx[not_won]),col]) - visited[not_won]
              product_f = np.sum(rest*mtx[not_won])* num
              not_won[board*5:board*5+col] = False
  return product_f

In [ ]:
print(which_lose(data,visited,line1))


1830.0


##DAY 5: Hydrothermal Venture

In [ ]:
def generate_lines(filePath, delimiters=[]):
    with open(filePath) as f:
        for line in f:
          line = line.strip() #removes newline character from end
          for d in delimiters:
            line =line.replace(d, ' ')
          yield line

In [ ]:
filePath = '/content/drive/MyDrive/AdventOfCode/input5.txt'
#filePath = '/content/drive/MyDrive/AdventOfCode/test.txt'
newfile = generate_lines(filePath, [',', '->'])
data = np.loadtxt(newfile, dtype=int)

In [ ]:
def filterout(data):
  mask = np.zeros(len(data), dtype=bool)
  for i in range(len(data)):
    if data[i][0] == data[i][2] or data[i][1] == data[i][3]:
      mask[i] = True
  return mask

def draw(data, board):
  for i in data:
    x =  np.array([i[0], i[2]])
    y =  np.array([i[1], i[3]])
    x.sort()
    y.sort()
    board[x[0]:x[1]+1,y[0]:y[1]+1] += 1
  tot = (board >= 2).sum()
  return tot, board

board = np.zeros([1000,1000])
mask = filterout(data)
truedata = data[mask]
tot, board = draw(truedata, board)
print(tot)

6007


In [ ]:
diagdata = data[~mask]

def diagcase(data, board):
  for i in data:
    corner, size, diagmtx = creatdiagmtx(i)
    x, y = corner[0], corner[1]
    board[x:x+size, y:y+size] += diagmtx
  tot = (board >= 2).sum()
  return tot, board

def creatdiagmtx(a):
  x1, y1, x2, y2 = a[0], a[1], a[2], a[3]
  size = np.absolute(x1-x2)+1
  corner =[x1,y1]
  diagmtx = np.identity(size) #np.fill_diagonal(zeromtx, 1)
  if x1 <= x2 and y1 >= y2:
    corner = [x1, y2]
    diagmtx = np.fliplr(diagmtx)
  if x1 >= x2 and y1 >= y2:
    corner = [x2, y2]
  if x1 >= x2 and y1 <= y2:
    corner = [x2, y1]
    diagmtx = np.fliplr(diagmtx)
  return corner, size, diagmtx

In [ ]:
tot, b = diagcase(diagdata, board)
print(tot)

19349
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
